<a href="https://colab.research.google.com/github/ardrapadmakumar/plant-disease-detection/blob/main/crop_disease.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing Libraries**

In [4]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

Unzipping dataset

In [ ]:
#import zipfile
#import os

# Path to your zip file in Google Drive
#zip_path = "/content/drive/MyDrive/dataset/crop_dataset/Crop_disease/crop_diesease/train.zip"

# Path to extract
#extract_path = "/content/drive/MyDrive/dataset/crop_dataset/Crop_disease/crop_diesease"

# Unzipping
#with zipfile.ZipFile(zip_path, 'r') as zip_ref:
#  zip_ref.extractall(extract_path)

#print("Extraction completed!")

Extraction completed!


To find no of files:

In [ ]:
import os

train_dir = "/content/drive/MyDrive/dataset/crop_dataset/Crop_disease/crop_diesease/train"

file_count = sum(len(files) for _, _, files in os.walk(train_dir))
print(f"Total files in train folder: {file_count}")

Total files in train folder: 41484


**Data Preprocessing**


Train- Image Preprocessing

In [5]:
training_set = tf.keras.utils.image_dataset_from_directory(
    '/content/drive/MyDrive/dataset/crop_dataset/Crop_disease/crop_diesease/train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    verbose=True,
)

Found 41483 files belonging to 38 classes.


Validation Image Processing

In [6]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    '/content/drive/MyDrive/dataset/crop_dataset/Crop_disease/crop_diesease/valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    verbose=True,
)

Found 17572 files belonging to 38 classes.


In [7]:
training_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [8]:
for x,y in training_set:
  print(x,x.shape)
  print(y,y.shape)
  break

tf.Tensor(
[[[[181.25 179.25 180.25]
   [179.75 177.75 178.75]
   [179.75 177.75 178.75]
   ...
   [192.25 190.25 191.25]
   [197.   195.   196.  ]
   [195.   193.   194.  ]]

  [[186.75 184.75 185.75]
   [181.25 179.25 180.25]
   [181.25 179.25 180.25]
   ...
   [197.   195.   196.  ]
   [193.75 191.75 192.75]
   [193.   191.   192.  ]]

  [[187.75 185.75 186.75]
   [182.5  180.5  181.5 ]
   [182.5  180.5  181.5 ]
   ...
   [197.5  195.5  196.5 ]
   [193.   191.   192.  ]
   [190.   188.   189.  ]]

  ...

  [[128.5  122.5  124.5 ]
   [142.   136.   138.  ]
   [131.75 125.75 127.75]
   ...
   [136.25 131.25 128.25]
   [138.5  133.5  130.5 ]
   [146.25 141.25 138.25]]

  [[141.25 135.25 137.25]
   [125.5  119.5  121.5 ]
   [129.75 123.75 125.75]
   ...
   [144.75 139.75 136.75]
   [144.5  139.5  136.5 ]
   [135.75 130.75 127.75]]

  [[135.   129.   131.  ]
   [132.75 126.75 128.75]
   [130.   124.   126.  ]
   ...
   [134.5  129.5  126.5 ]
   [144.   139.   136.  ]
   [144.   139.   13

**Building model**

In [9]:
from tensorflow.keras.layers import Dense,Conv2D,MaxPool2D, Dropout
from tensorflow.keras.models import Sequential

In [10]:
model=Sequential()

Building Convolution Layer

In [11]:
model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=32,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [12]:
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=64,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [13]:
model.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=128,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [14]:
model.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=256,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [15]:
model.add(Conv2D(filters=512,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=512,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [16]:
model.add(Dropout(0.25)) #To avoid overfitting

In [17]:
model.add(tf.keras.layers.Flatten())

In [18]:
model.add(Dense(units=1500,activation='relu'))

In [19]:
model.add(Dropout(0.4))

**Output Layer**

In [20]:
model.add(Dense(units=38,activation='softmax'))

**Compiling model**

In [21]:
model.compile(optimizer=tf.keras.optimizers.Adam(
    learning_rate=0.0001),loss='categorical_crossentropy',metrics=['accuracy'])

In [22]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 128, 128, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 126, 126, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 63, 63, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 63, 63, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 61, 61, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 30, 30, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 30, 30, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 28, 28, 128)    │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 14, 14, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_6 (Conv2D)               │ (None, 14, 14, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_7 (Conv2D)               │ (None, 12, 12, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 6, 6, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_8 (Conv2D)               │ (None, 6, 6, 512)      │     1,180,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_9 (Conv2D)               │ (None, 4, 4, 512)      │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_4 (MaxPooling2D)  │ (None, 2, 2, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 2, 2, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1500)           │     3,073,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 1500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 38)             │        57,038 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,842,762 (29.92 MB)

 Trainable params: 7,842,762 (29.92 MB)

 Non-trainable params: 0 (0.00 B)

**Training model**

In [ ]:
training_history=model.fit(x=training_set,validation_data=validation_set,epochs=10)

**Model Evaluation**

Evaluation on training set

In [ ]:
train_loss, train_acc = model.evaluate(training_set)

In [ ]:
print(train_loss,train_acc)

Evaluation on Validation Set

In [ ]:
val_loss, val_acc = model.evaluate(validation_set)

In [ ]:
print(val_loss,val_acc)

**Saving Model**

In [26]:
model.save("trained_model.keras")

In [27]:
training_history.history

NameError: name 'training_history' is not defined

Recording History in json

In [ ]:
import json
with open("training_hist.json","w") as f:
  json.dump(training_history.history,f)

**Accuracy Visualization**

In [ ]:
epochs = [i for i in range(1,11)]
plt.plot(epochs,training_history.history['accuracy'],color='red',label='Training Accuracy')
plt.plot(epochs,training_history.history['val_accuracy'],color='blue',label='Validation Accuracy')
plt.xlabel("No of epochs")
plt.ylabel("Accuracy Result")
plt.title("Visualization of Accuracy Result")
plt.legend()
plt.show()